replicaCount: 1

image:
  repository: vectornguyen76/backend_search_engine
  # Always and latest for dev, IfNotPresent for prod
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

env:
  - name: IMAGE_SEARCH_URL
    value: http://image-search-app.application:7000
  - name: TEXT_SEARCH_URL
    value: http://text-search-app.application:6000
  - name: POSTGRES_HOST
    value: database-postgresql.database
  - name: POSTGRES_DB
    value: db_dev
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        key: POSTGRES_USER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        key: PGPASSWORD
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        key: JWT_SECRET


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi

secret:
  userName: db_user
  postgresPassword: db_password
  databaseUrl: postgresql+asyncpg://db_user:db_password@database-postgresql.database/db_dev
  jwtSecret: my-jwt-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: search.vectornguyen.com
      paths:
        - path: /backend/?(.*)
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
