apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-search-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-search
  template:
    metadata:
      labels:
        app: image-search
    spec:
      containers:
        - name: image-search-container
          image: vectornguyen76/image_search:latest
          imagePullPolicy: Always
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 7000
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          env:
            - name: QDRANT_URL
              value: "http://qdrant-db.default:6334"
            - name: TRITON_SERVER_URL
              value: "model-serving-triton-inference-server.default:8001"
          ports:
            - containerPort: 7000
      nodeSelector:
        nodegroup-type: cpu-nodegroup
