apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.userName | b64enc }}
  PGPASSWORD: {{ .Values.secret.postgresPassword | b64enc }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc }}