name: build_images

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image search
        uses: docker/build-push-action@v4
        with:
          context: ./image_search
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image_search:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push text search
        uses: docker/build-push-action@v4
        with:
          context: ./text_search
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/text_search:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend_search_engine:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend_search_engine:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
