name: continuous_integration

on:
  workflow_call:

jobs:
  build-test-image-search:
    runs-on: ubuntu-latest
    services:
      qdrant:
        image: qdrant/qdrant:v1.9.0
        ports:
          - 6334:6334
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install Dependencies
        working-directory: image_search
        run: |
          pip install -r requirements.txt

      - name: Run ruff
        run: ruff check image_search

  build-test-text-search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install Dependencies
        working-directory: text_search
        run: |
          pip install -r requirements.txt

      - name: Run ruff
        run: ruff check text_search

  build-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: Run ruff
        run: ruff check backend

  build-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Build frontend
        working-directory: frontend
        run: pnpm run build
