name: rollback

on:
  workflow_call:
    inputs:
      stack_name:
        description: "The stack name to destroy"
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get stack name
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "FULL_STACK_NAME=${{ inputs.stack_name }}-${{ env.SHA_SHORT }}" >> "$GITHUB_ENV"

      - name: Remove failed stack
        run: |
          if aws cloudformation describe-stacks --stack-name ${{ env.FULL_STACK_NAME }} >/dev/null 2>&1; then
            aws cloudformation delete-stack --stack-name ${{ env.FULL_STACK_NAME }}
            aws cloudformation wait stack-delete-complete --stack-name ${{ env.FULL_STACK_NAME }}
          else
            echo "Stack ${{ env.FULL_STACK_NAME }} does not exist"
          fi
