replicaCount: 1

image:
  repository: vectornguyen76/image_search
  # Always and latest for dev, IfNotPresent for prod
  pullPolicy: Always
  tag: "latest"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: ClusterIP
  port: 7000

env:
  - name: QDRANT_URL
    value: "http://qdrant.database:6334"
  - name: TRITON_SERVER_URL
    value: "model-serving-triton-inference-server.model-serving:8001"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}